DROP TABLE IF EXISTS `Plugin`;
CREATE TABLE IF NOT EXISTS `Plugin` (
   ServerId VARCHAR(18) NOT NULL,
   ModuleAr BOOLEAN NOT NULL DEFAULT false,
   ModuleMo BOOLEAN NOT NULL DEFAULT false,
   ModuleLv BOOLEAN NOT NULL DEFAULT false,
   ModuleEc BOOLEAN NOT NULL DEFAULT false,
   ModuleWc BOOLEAN NOT NULL DEFAULT false,
   PRIMARY KEY(ServerId)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Channel`;
CREATE TABLE IF NOT EXISTS `Channel` (
   ServerId VARCHAR(18) NOT NULL,
   WelcomeChannel VARCHAR(18) NOT NULL DEFAULT 'Indéfini',
   GoodbyeChannel VARCHAR(18) NOT NULL DEFAULT 'Indéfini',
   RankupsChannel VARCHAR(18) NOT NULL DEFAULT 'Indéfini',
   SkippedChannel1 VARCHAR(18) NOT NULL DEFAULT 'Indéfini',
   SkippedChannel2 VARCHAR(18) NOT NULL DEFAULT 'Indéfini',
   SkippedChannel3 VARCHAR(18) NOT NULL DEFAULT 'Indéfini',
   PRIMARY KEY(ServerId)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `AntiRaid`;
CREATE TABLE IF NOT EXISTS `AntiRaid` (
   ServerId VARCHAR(18) NOT NULL,
   JoinLimit INT NOT NULL DEFAULT 3,
   JoinTimeout INT NOT NULL DEFAULT 10000,
   JoinSantion VARCHAR(4) NOT NULL DEFAULT 'KICK',
   PRIMARY KEY(ServerId)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Leveling`;
CREATE TABLE IF NOT EXISTS `Leveling` (
   MemberId VARCHAR(18) NOT NULL,
   Ladder INT NOT NULL DEFAULT 1,
   Booster CHAR(1) NOT NULL DEFAULT 'D',
   XpFarmed INT NOT NULL DEFAULT 0,
   XpNeeded INT NOT NULL DEFAULT 200,
   PRIMARY KEY(MemberId)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Economy`;
CREATE TABLE IF NOT EXISTS `Economy` (
   MemberId VARCHAR(18) NOT NULL,
   Wallet INT NOT NULL DEFAULT 2000,
   Bank INT NOT NULL DEFAULT 0,
   Casino INT NOT NULL DEFAULT 3,
   PRIMARY KEY(MemberId)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Sanction`;
CREATE TABLE IF NOT EXISTS `Sanction` (
   MemberId VARCHAR(18) NOT NULL,
   ServerId VARCHAR(18) NOT NULL,
   ModId VARCHAR(18) NOT NULL,
   Sanction VARCHAR(4) NOT NULL DEFAULT 'VOID',
   Reason VARCHAR(100) NOT NULL DEFAULT 'Aucune description enregistrée',
   PRIMARY KEY(MemberId)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Server`;
CREATE TABLE IF NOT EXISTS `Server` (
   ServerId VARCHAR(18) NOT NULL,
   ServerId_FK1 VARCHAR(18) NOT NULL,
   ServerId_FK2 VARCHAR(18) NOT NULL,
   ServerId_FK3 VARCHAR(18) NOT NULL,
   PRIMARY KEY(ServerId),
   FOREIGN KEY(ServerId_FK1) REFERENCES AntiRaid(ServerId),
   FOREIGN KEY(ServerId_FK2) REFERENCES Channel(ServerId),
   FOREIGN KEY(ServerId_FK3) REFERENCES Plugin(ServerId)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Member`;
CREATE TABLE IF NOT EXISTS `Member` (
   MemberId VARCHAR(18) NOT NULL,
   About VARCHAR(200) NOT NULL DEFAULT 'Aucune description enregistrée',
   JoinCounter INT NOT NULL DEFAULT 0,
   MemberId_FK1 VARCHAR(18) NOT NULL,
   MemberId_FK2 VARCHAR(18) NOT NULL,
   PRIMARY KEY(MemberId),
   FOREIGN KEY(MemberId_FK1) REFERENCES Economy(MemberId),
   FOREIGN KEY(MemberId_FK2) REFERENCES Leveling(MemberId)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;