DROP TABLE IF EXISTS `Staffs`;
CREATE TABLE IF NOT EXISTS `Staffs` (
   StaffId VARCHAR(18) NOT NULL,
   SPPoints INT NOT NULL DEFAULT 0,
   MOPoints INT NOT NULL DEFAULT 0,
   ARPoints INT NOT NULL DEFAULT 0,
   TKClaimed INT NOT NULL DEFAULT 0,
   TUAmount INT NOT NULL DEFAULT 0,
   TDAmount INT NOT NULL DEFAULT 0, 
   PRIMARY KEY(StaffId)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Tickets`;
CREATE TABLE IF NOT EXISTS `Tickets` (
   TicketId INT NOT NULL,
   OwnerId VARCHAR(18) NOT NULL,
   Handled VARCHAR(18) NOT NULL,
   PRIMARY KEY(TicketId)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;