DROP TABLE IF EXISTS `Staffs`;
CREATE TABLE IF NOT EXISTS `Staffs` (
   StaffId VARCHAR(18) NOT NULL,
   SPLevel INT NOT NULL DEFAULT 1,
   SPPoints INT NOT NULL DEFAULT 0,
   SPRequired INT NOT NULL DEFAULT 5,
   MOLevel INT NOT NULL DEFAULT 1,
   MOPoints INT NOT NULL DEFAULT 0,
   MORequired INT NOT NULL DEFAULT 5,
   ARLevel INT NOT NULL DEFAULT 1,
   ARPoints INT NOT NULL DEFAULT 0,
   ARRequired INT NOT NULL DEFAULT 5,
   TKClaimed INT NOT NULL DEFAULT 0,
   TUAmount INT NOT NULL DEFAULT 0,
   TULevel INT NOT NULL DEFAULT 1,
   TURequired INT NOT NULL DEFAULT 10,
   TDAmount INT NOT NULL DEFAULT 0, 
   PRIMARY KEY(StaffId)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

DROP TABLE IF EXISTS `Tickets`;
CREATE TABLE IF NOT EXISTS `Tickets` (
   TicketId INT NOT NULL,
   OwnerId VARCHAR(18) NOT NULL,
   Handled VARCHAR(18) NOT NULL,
   PRIMARY KEY(TicketId)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;